### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Juris3D** [KristofMorva/blueprint-streams#1]
Hello. I bought plugin. Please could we have some guides, documentation, about usage scenarios. Thank You.

**Comment by KristofMorva** [comment]
Hey, I have extended the details of the marketplace page with some examples, I hope it's clearer now what is it good for exactly. This example project contains some practical examples (like the save system), but if you have a generic enough scenario in mind, for which data streams would be helpful in Blueprints (and is not included yet), contact me :)
